name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  flip_card: ^0.7.0
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true