name: Parseit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  flip_card: ^0.7.0
  flutter_tts: ^4.2.5
  uuid: ^4.5.2
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    backgroundColor: "#ffffff"
    theme_color: "#000000"